name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install test dependencies
      run: |
        sudo apt-get update
        sudo apt-get install check 
    - name: Compile and run tests
      run: |
        cd tests
        make clean
        make
